require "user.plugins"
require "user.navic"
require "user.winbar"
require "user.autocommands"
require "user.options"
require "user.cmp"
require "user.bookmarks"
require "user.custom_dap"
require "user.lsp"
require "user.alpha"
require "user.dressing"
require "user.notify"
require "user.colorizer"
require "user.nvim-tree"
require "user.line"
require "user.utils.plugin.toggleterm"
require "user.utils.plugin.treesitter"
-- require "user.utils.plugin.surround"
require "user.utils.plugin.project"
-- require "user.utils.plugin.identline"
-- require "user.gps"
-- require "user.illuminate"
-- require "user.fidget"
-- require "user.impatient"
-- require "user.lsp-inlayhints"
-- require "user.numb"
-- require "user.neogit"
