require "user.plugins"
require "user.navic"
require "user.winbar"
require "user.autocommands"
require "user.options"
require "user.cmp"
require "user.bookmarks"
require "user.custom_dap"
require "user.lsp"
require "user.alpha"
require "user.dressing"
require "user.notify"
require "user.colorizer"
-- require "user.gps"
-- require "user.illuminate"
-- require "user.fidget"
-- require "user.impatient"
-- require "user.lsp-inlayhints"
-- require "user.numb"
-- require "user.neogit"
